### PR TITLE
Use `@wbetools.patch` on early chapters

### PR DESCRIPTION
**Pull request by pavpanchekha**
This PR deletes a bunch of duplicate code from earlier chapters using the `wbetools.patch` code. It has to delete one test which relies on running `lab6` and `lab7` in parallel to get two different layouts. It also pulls in an improved version of `wbetools.patch`, which was originally written for Chapter 16.

### CODE REVIEW

**Comment by pavpanchekha** [comment]
This can't be merged right now because the compiler doesn't support patches.

**Comment by pavpanchekha** [comment]
Everything now works _except_ that while the compiler supports patching, it doesn't support patching functions. Which is frustrating!

**Comment by pavpanchekha** [comment]
Ok, I changed Chapter 8 to not require patches. This does kind-of work, but it really only sets us up for more complications if we ever get labs 15 & 16 working, since they also patch functions. Still, even if eventually we find we cannot patch functions, only classes, I think it won't be so bad to inline all of their callers.

**Comment by pavpanchekha** [comment]
Ok, @chrishtr—this uses `@wbetools.patch` in a normal, standard way to get rid of about 1k lines of duplicate code throughout Chapters 1–11. The hope is that this makes cross-chapter changes easier.

One challenge I did run into is that the compiler doesn't support `patch`ing functions. If it did, we could delete some more duplicate code. But I tried for a while and I don't think JS makes this possible, and even in Python, it's pretty shady. Anyway for now I didn't use it, just more basic patching of classes.

**Review by chrishtr — APPROVED** [review]

**Pull request merged**
