### PR TITLE
Add a paragraph to the preface calling out that software has bugs

### PR DESCRIPTION
**Pull request by chrishtr**

### CODE REVIEW

**Comment by pavpanchekha** [comment]
You know, the text is fine, but I'm kind of against adding this. I think it's fair to say there might be bugs, where to report them, and where to get an up-to-date copy of the book/code, but I think we should stand behind our code more than this paragraph does! And, like, set a high bar for ourselves.

**Review by pavpanchekha — COMMENTED** [review]
(see comment above)

**Review by pavpanchekha — CHANGES_REQUESTED** [review]
(see comment two above—GH interface is confusing me.)

**Comment by chrishtr** [comment]
ok. Closing then.

**Pull request closed without merging**
